ALTER TABLE `users` ADD COLUMN `street` VARCHAR(255) NOT NULL;
ALTER TABLE `users` ADD COLUMN `zip_code` VARCHAR(255) NOT NULL;
ALTER TABLE `users` ADD COLUMN `emergency_contact` VARCHAR(255) NOT NULL;
ALTER TABLE `users` ADD COLUMN `emergency_contact_phone` VARCHAR(255) NOT NULL;
ALTER TABLE `users` ADD COLUMN `allergies` VARCHAR(511) NOT NULL;
ALTER TABLE `users` ADD COLUMN `medicines` VARCHAR(511) NOT NULL;
ALTER TABLE `users` ADD COLUMN `date_of_birth` VARCHAR(255) NOT NULL;